language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all


before_script:
- ! 'pip install ''travis-cargo<0.2'' --user &&
  export PATH=$HOME/.local/bin:$PATH
'
script:
- ! 'travis-cargo build &&
  travis-cargo test &&
  travis-cargo bench &&
  travis-cargo --only nightly doc
'

after_success:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo coveralls --no-sudo --verify; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./kcov/build/src/kcov --verify --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/diesel_ext-*; fi
